### ISSUE TITLE
Failure : Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created

### ISSUE THREAD

**Issue by jmvanel** [agreementmaker/agreementmaker#17]
I applied the procedure on the wiki to run AgreementMaker as an OSGi run config.

Here are the messages in the eclipse console.
( note that subsequently trying to load an RDF/XML fails and empty OWL properties and classe are show in the tree view )

```
Matcher-OAEI starting...
 The environment variable AM_ROOT is not set.  Using working directory as our root.
 AgreementMaker root directory: /home/jmv
!SESSION 2015-11-06 15:58:45.956 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr_FR
Command-line arguments:  -dev file:/home/jmv/workspace/.metadata/.plugins/org.eclipse.pde.core/AgreementMaker/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog

!ENTRY Matcher-OAEI 4 0 2015-11-06 15:58:48.871
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Exception in am.matcher.oaei.OAEIMatcherBundleActivator.start() of bundle Matcher-OAEI.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:792)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:311)
	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)
	at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:120)
	at java.util.prefs.XmlSupport.loadPrefsDoc(XmlSupport.java:241)
	at java.util.prefs.XmlSupport.importMap(XmlSupport.java:375)
	at java.util.prefs.FileSystemPreferences$6.run(FileSystemPreferences.java:575)
	at java.util.prefs.FileSystemPreferences$6.run(FileSystemPreferences.java:568)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.prefs.FileSystemPreferences.loadCache(FileSystemPreferences.java:567)
	at java.util.prefs.FileSystemPreferences.initCacheIfNecessary(FileSystemPreferences.java:550)
	at java.util.prefs.FileSystemPreferences.getSpi(FileSystemPreferences.java:527)
	at java.util.prefs.AbstractPreferences.get(AbstractPreferences.java:287)
	at am.utility.AppPreferences.getRecentFileName(AppPreferences.java:586)
	at am.utility.AppPreferences.cleanUpFileEntries(AppPreferences.java:423)
	at am.utility.AppPreferences.cleanUpFileEntries(AppPreferences.java:408)
	at am.utility.AppPreferences.<init>(AppPreferences.java:99)
	at am.app.Core.<init>(Core.java:169)
	at am.app.Core.<clinit>(Core.java:118)
	at am.app.mappingEngine.AbstractMatcher.initializeVariables(AbstractMatcher.java:268)
	at am.app.mappingEngine.AbstractMatcher.<init>(AbstractMatcher.java:232)
	at am.matcher.oaei.oaei2009.OAEI2009matcher.<init>(OAEI2009matcher.java:40)
	at am.matcher.oaei.OAEIMatcherBundleActivator.start(OAEIMatcherBundleActivator.java:38)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	... 12 more
Caused by: java.lang.RuntimeException: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:308)
	... 37 more
Caused by: java.util.ServiceConfigurationError: javax.xml.parsers.DocumentBuilderFactory: Provider org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)
	... 37 more
Root exception:
javax.xml.parsers.FactoryConfigurationError: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:311)
	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)
	at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:120)
	at java.util.prefs.XmlSupport.loadPrefsDoc(XmlSupport.java:241)
	at java.util.prefs.XmlSupport.importMap(XmlSupport.java:375)
	at java.util.prefs.FileSystemPreferences$6.run(FileSystemPreferences.java:575)
	at java.util.prefs.FileSystemPreferences$6.run(FileSystemPreferences.java:568)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.prefs.FileSystemPreferences.loadCache(FileSystemPreferences.java:567)
	at java.util.prefs.FileSystemPreferences.initCacheIfNecessary(FileSystemPreferences.java:550)
	at java.util.prefs.FileSystemPreferences.getSpi(FileSystemPreferences.java:527)
	at java.util.prefs.AbstractPreferences.get(AbstractPreferences.java:287)
	at am.utility.AppPreferences.getRecentFileName(AppPreferences.java:586)
	at am.utility.AppPreferences.cleanUpFileEntries(AppPreferences.java:423)
	at am.utility.AppPreferences.cleanUpFileEntries(AppPreferences.java:408)
	at am.utility.AppPreferences.<init>(AppPreferences.java:99)
	at am.app.Core.<init>(Core.java:169)
	at am.app.Core.<clinit>(Core.java:118)
	at am.app.mappingEngine.AbstractMatcher.initializeVariables(AbstractMatcher.java:268)
	at am.app.mappingEngine.AbstractMatcher.<init>(AbstractMatcher.java:232)
	at am.matcher.oaei.oaei2009.OAEI2009matcher.<init>(OAEI2009matcher.java:40)
	at am.matcher.oaei.OAEIMatcherBundleActivator.start(OAEIMatcherBundleActivator.java:38)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.RuntimeException: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:308)
	... 37 more
```

**Comment by cstroe** [comment]
Hi @jmvanel, it seems that the error you have shown above might be auxiliary to the real problem.  If you mention that the nodes are empty in the UI, this seems like it's more of a problem of selecting the correct ontology language and syntax.

See this comment: https://github.com/agreementmaker/agreementmaker/issues/11#issuecomment-149605746

Do you happen to have a link to the ontologies you're loading?

**Comment by cstroe** [comment]
@jmvanel: I just update AgreementMaker so that it can run directly from the command line.  Instructions are here: https://github.com/agreementmaker/agreementmaker#running. Can you please try this way of running AgreementMaker and see if it fixes the issue?

**Comment by cstroe** [comment]
Closing this as it cannot be reproduced.
