### ISSUE TITLE
Loading Ontologies Error

### ISSUE THREAD

**Issue by ctmartins** [agreementmaker/agreementmaker#7]
I'm having a problem when opening ontologies with AgreementMaker graphical user interface. When I try to load the following ontologies an error appears and the ontologies aren't loaded. The ontologies are human an mouse ontologies with the URL: http://purl.bioontology.org/ontology/NCIT and http://purl.obolibrary.org/obo/ma.owl.
The error that appears in eclipse is:

AgreementMaker-UserFeedback starting...
 Opening file: http://purl.bioontology.org/ontology/NCIT
Reading Model...Done
javax.xml.parsers.FactoryConfigurationError: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:311)
	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)
	at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:120)
	at sun.util.xml.PlatformXmlPropertiesProvider.getLoadingDoc(PlatformXmlPropertiesProvider.java:96)
	at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:78)
	at java.util.Properties$XmlSupport.load(Properties.java:1201)
	at java.util.Properties.loadFromXML(Properties.java:881)
	at com.hp.hpl.jena.util.Metadata.read(Metadata.java:76)
	at com.hp.hpl.jena.util.Metadata.addMetadata(Metadata.java:54)
	at com.hp.hpl.jena.util.Metadata.<init>(Metadata.java:48)
	at com.hp.hpl.jena.JenaRuntime.<clinit>(JenaRuntime.java:34)
	at com.hp.hpl.jena.rdf.model.impl.RDFReaderFImpl.reset(RDFReaderFImpl.java:82)
	at com.hp.hpl.jena.rdf.model.impl.RDFReaderFImpl.<clinit>(RDFReaderFImpl.java:75)
	at com.hp.hpl.jena.rdf.model.impl.ModelCom.<clinit>(ModelCom.java:54)
	at com.hp.hpl.jena.rdf.model.ModelFactory.createDefaultModel(ModelFactory.java:140)
	at com.hp.hpl.jena.vocabulary.OWL.<clinit>(OWL.java:36)
	at com.hp.hpl.jena.ontology.ProfileRegistry.<clinit>(ProfileRegistry.java:43)
	at com.hp.hpl.jena.ontology.OntModelSpec.<clinit>(OntModelSpec.java:49)
	at am.app.ontology.ontologyParser.RdfsTreeBuilder.buildTree(RdfsTreeBuilder.java:68)
	at am.app.ontology.ontologyParser.TreeBuilder.build(TreeBuilder.java:182)
	at am.app.ontology.ontologyParser.TreeBuilder.doInBackground(TreeBuilder.java:327)
	at am.app.ontology.ontologyParser.TreeBuilder.doInBackground(TreeBuilder.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:308)
	... 27 more
Caused by: java.util.ServiceConfigurationError: javax.xml.parsers.DocumentBuilderFactory: Provider org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)
	... 27 more
 Opening file: http://purl.obolibrary.org/obo/ma.owl
Reading Model...Done
java.lang.NoClassDefFoundError: Could not initialize class com.hp.hpl.jena.ontology.OntModelSpec
	at am.app.ontology.ontologyParser.RdfsTreeBuilder.buildTree(RdfsTreeBuilder.java:68)
	at am.app.ontology.ontologyParser.TreeBuilder.build(TreeBuilder.java:182)
	at am.app.ontology.ontologyParser.TreeBuilder.doInBackground(TreeBuilder.java:327)
	at am.app.ontology.ontologyParser.TreeBuilder.doInBackground(TreeBuilder.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cstroe** [comment]
Hi @ctmartins, 

The URL http://purl.bioontology.org/ontology/NCIT does not link to a proper OWL ontology.  It links to a web interface to the ontology, which is not readable by AgreementMaker.

Do you have a link to the proper OWL ontology?

**Comment by ctmartins** [comment]
Try this one: http://data.bioontology.org/ontologies/NCIT/submissions/41/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb
OBO foundry just had the obo version so I had to find the owl one. I found that link in Bioportal (http://bioportal.bioontology.org/ontologies/NCIT). I am not sure it is the right one

**Comment by cstroe** [comment]
The NCIT ontology is 250 mb, which is too large for normal loading.  I will try to use large ontology mode, but it has a bug right now, which I will have to fix.

**Comment by ctmartins** [comment]
I tried it with smaller ontologies and I still have problems.
I used the dataset from OAEI: http://oaei.ontologymatching.org/2015/conference/index.html
The error that appeared was:

AgreementMaker-UserFeedback starting...
 Opening file: C:\Users\Catarina\workspace\AgreementMakerLight_mine\store\conference\edas.owl
Reading Model...Done
javax.xml.parsers.FactoryConfigurationError: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:311)
	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)
	at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:120)
	at sun.util.xml.PlatformXmlPropertiesProvider.getLoadingDoc(PlatformXmlPropertiesProvider.java:96)
	at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:78)
	at java.util.Properties$XmlSupport.load(Properties.java:1201)
	at java.util.Properties.loadFromXML(Properties.java:881)
	at com.hp.hpl.jena.util.Metadata.read(Metadata.java:76)
	at com.hp.hpl.jena.util.Metadata.addMetadata(Metadata.java:54)
	at com.hp.hpl.jena.util.Metadata.<init>(Metadata.java:48)
	at com.hp.hpl.jena.JenaRuntime.<clinit>(JenaRuntime.java:34)
	at com.hp.hpl.jena.rdf.model.impl.RDFReaderFImpl.reset(RDFReaderFImpl.java:82)
	at com.hp.hpl.jena.rdf.model.impl.RDFReaderFImpl.<clinit>(RDFReaderFImpl.java:75)
	at com.hp.hpl.jena.rdf.model.impl.ModelCom.<clinit>(ModelCom.java:54)
	at com.hp.hpl.jena.rdf.model.ModelFactory.createDefaultModel(ModelFactory.java:140)
	at com.hp.hpl.jena.vocabulary.OWL.<clinit>(OWL.java:36)
	at com.hp.hpl.jena.ontology.ProfileRegistry.<clinit>(ProfileRegistry.java:43)
	at com.hp.hpl.jena.ontology.OntModelSpec.<clinit>(OntModelSpec.java:49)
	at am.app.ontology.ontologyParser.RdfsTreeBuilder.buildTree(RdfsTreeBuilder.java:68)
	at am.app.ontology.ontologyParser.TreeBuilder.build(TreeBuilder.java:182)
	at am.app.ontology.ontologyParser.TreeBuilder.doInBackground(TreeBuilder.java:327)
	at am.app.ontology.ontologyParser.TreeBuilder.doInBackground(TreeBuilder.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:308)
	... 27 more
Caused by: java.util.ServiceConfigurationError: javax.xml.parsers.DocumentBuilderFactory: Provider org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)
	... 27 more
 Opening file: C:\Users\Catarina\workspace\AgreementMakerLight_mine\store\conference\ekaw.owl
Reading Model...Done
java.lang.NoClassDefFoundError: Could not initialize class com.hp.hpl.jena.ontology.OntModelSpec
	at am.app.ontology.ontologyParser.RdfsTreeBuilder.buildTree(RdfsTreeBuilder.java:68)
	at am.app.ontology.ontologyParser.TreeBuilder.build(TreeBuilder.java:182)
	at am.app.ontology.ontologyParser.TreeBuilder.doInBackground(TreeBuilder.java:327)
	at am.app.ontology.ontologyParser.TreeBuilder.doInBackground(TreeBuilder.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cstroe** [comment]
I have no problem loading the `ekaw.owl` ontology:
![am-load](https://cloud.githubusercontent.com/assets/1182093/10761577/072e716a-7c90-11e5-8171-1068f6367fd1.png)

In the file load dialog, make sure you select the correct ontology language and syntax.  It should be `OWL` and `RDF/XML`.

The loading issue is the same as https://github.com/agreementmaker/agreementmaker/issues/11

**Comment by ctmartins** [comment]
I tried it but is giving this error in the console:
AgreementMaker-UserFeedback starting...
 Opening file: C:\Users\Catarina\workspace\AgreementMakerLight_mine\store\conference\ekaw.owl
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.hp.hpl.jena.rdf.model.impl.IO_Ctl.callByRefection(IO_Ctl.java:64)
	at com.hp.hpl.jena.rdf.model.impl.IO_Ctl.init(IO_Ctl.java:36)
	at com.hp.hpl.jena.util.FileManager.<clinit>(FileManager.java:87)
	at am.app.ontology.ontologyParser.OntoTreeBuilder.buildTreeNoReasoner(OntoTreeBuilder.java:244)
	at am.app.ontology.ontologyParser.OntoTreeBuilder.buildTreeDefault(OntoTreeBuilder.java:167)
	at am.app.ontology.ontologyParser.OntoTreeBuilder.buildTree(OntoTreeBuilder.java:136)
	at am.app.ontology.ontologyParser.OntoTreeBuilder.buildTree(OntoTreeBuilder.java:116)
	at am.app.ontology.ontologyParser.TreeBuilder.build(TreeBuilder.java:182)
	at am.app.ontology.ontologyParser.TreeBuilder.doInBackground(TreeBuilder.java:327)
	at am.app.ontology.ontologyParser.TreeBuilder.doInBackground(TreeBuilder.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:311)
	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)
	at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:120)
	at sun.util.xml.PlatformXmlPropertiesProvider.getLoadingDoc(PlatformXmlPropertiesProvider.java:96)
	at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:78)
	at java.util.Properties$XmlSupport.load(Properties.java:1201)
	at java.util.Properties.loadFromXML(Properties.java:881)
	at com.hp.hpl.jena.util.Metadata.read(Metadata.java:76)
	at com.hp.hpl.jena.util.Metadata.addMetadata(Metadata.java:54)
	at com.hp.hpl.jena.util.Metadata.<init>(Metadata.java:48)
	at com.hp.hpl.jena.JenaRuntime.<clinit>(JenaRuntime.java:34)
	at org.apache.jena.riot.stream.JenaIOEnvironment.getGlobalConfigPath(JenaIOEnvironment.java:70)
	at org.apache.jena.riot.stream.JenaIOEnvironment.getLocationMapper(JenaIOEnvironment.java:46)
	at org.apache.jena.riot.stream.StreamManager.makeDefaultStreamManager(StreamManager.java:73)
	at org.apache.jena.riot.stream.StreamManager.<clinit>(StreamManager.java:85)
	at org.apache.jena.riot.adapters.AdapterFileManager.makeGlobal(AdapterFileManager.java:148)
	at org.apache.jena.riot.adapters.AdapterFileManager.get(AdapterFileManager.java:107)
	at org.apache.jena.riot.IO_Jena.wireIntoJena(IO_Jena.java:37)
	at org.apache.jena.riot.RIOT.init(RIOT.java:66)
	... 20 more
Caused by: java.lang.RuntimeException: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:308)
	... 38 more
Caused by: java.util.ServiceConfigurationError: javax.xml.parsers.DocumentBuilderFactory: Provider org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)
	... 38 more
Done
java.lang.NoClassDefFoundError: Could not initialize class com.hp.hpl.jena.JenaRuntime
	at com.hp.hpl.jena.util.LocationMapper.getGlobalConfigPath(LocationMapper.java:243)
	at com.hp.hpl.jena.util.LocationMapper.get(LocationMapper.java:70)
	at com.hp.hpl.jena.util.FileManager.makeGlobal(FileManager.java:147)
	at com.hp.hpl.jena.util.FileManager.get(FileManager.java:96)
	at am.app.ontology.ontologyParser.OntoTreeBuilder.buildTreeNoReasoner(OntoTreeBuilder.java:244)
	at am.app.ontology.ontologyParser.OntoTreeBuilder.buildTreeDefault(OntoTreeBuilder.java:167)
	at am.app.ontology.ontologyParser.OntoTreeBuilder.buildTree(OntoTreeBuilder.java:136)
	at am.app.ontology.ontologyParser.OntoTreeBuilder.buildTree(OntoTreeBuilder.java:116)
	at am.app.ontology.ontologyParser.TreeBuilder.build(TreeBuilder.java:182)
	at am.app.ontology.ontologyParser.TreeBuilder.doInBackground(TreeBuilder.java:327)
	at am.app.ontology.ontologyParser.TreeBuilder.doInBackground(TreeBuilder.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
An the GUI stays like this:

![error](https://github-cloud.s3.amazonaws.com/assets%2F13274093%2F10957517%2Feb9dba72-835c-11e5-943e-1bad2e4553fb.png)

**Comment by cstroe** [comment]
@ctmartins, I updated the way AgreementMaker can be run, so now it can run directly from the command line with just one command.  No need to setup any Eclipse workspace.

The instructions are here: https://github.com/agreementmaker/agreementmaker#running

Could you try running AgreementMaker in this way, I have a feeling it might fix your issue.  Please try and let me know.

**Comment by ctmartins** [comment]
Sorry for the late answer. I will try it out. Do you recommend doing it on windows or linux?
Thank you.

**Comment by cstroe** [comment]
@ctmartins: It's all based on Maven, so it should work on either.  As for me, I don't have any experience with developing/running AgreementMaker on Windows, only Linux.  So if you could test in Linux, it would help us troubleshoot.
